[nfs]
172.31.9.79 ansible_ssh_user='ec2-user'

[webservers]
172.31.3.223 ansible_ssh_user='ec2-user'
172.31.13.214 ansible_ssh_user='ec2-user'

[db]
172.31.11.29 ansible_ssh_user='ubuntu' 

[lb]
172.31.40.0 ansible_ssh_user='ubuntu'

