[nfs]
172.31.9.79 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=/home/ubuntu/Red-hat.pem

[webservers]
172.31.3.223 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=/home/ubuntu/Red-hat.pem
172.31.13.214 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=/home/ubuntu/Red-hat.pem

[db]
172.31.11.29 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=/home/ubuntu/Ubuntu-login.pem

[lb]
172.31.40.0 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=/home/ubuntu/Ubuntu-login.pem

