- name: install apache
  yum:
    name: httpd
    state: present
  become: true

- name: install git
  yum:
    name: git
    state: present
  become: true

- name: clone a repo
  git:
    repo: https://github.com/srinath013/tooling.git
    dest: /var/www/html
    force: yes
  become: true

- name: Ensure /var/www/ exists
  file:
    path: /var/www/
    state: directory
    mode: '0755'
  become: true

- name: copy html content to one level up
  command: cp -r /var/www/html/html/ /var/www/
  become: true

- name: Ensure httpd service is started and enabled
  service:
    name: httpd
    state: started
    enabled: true
  become: true

- name: recursively remove /var/www/html/html/ directory
  file:
    path: /var/www/html/html
    state: absent
  become: true

